### PR TITLE
Tensorflow conversion

### PR DESCRIPTION
**Pull request by SuperShinyEyes**
Add a Tensorflow front-end.

### CODE REVIEW

**Comment by BachiLi** [comment]
Cool!! Let me test it and I'll merge it with the master.

**Comment by BachiLi** [comment]
Works on my machine. I'll make two changes before merging: 1. I'll try to get rid of the scatter_add custom op if possible. 2. I'll add GPU support.

**Comment by BachiLi** [comment]
> **DO NOT use `tf.zeros` or `tf.zeros_like`.**.
> 
> Tensorflow has a very strange bug. When I run `test_g_buffer.py`, `tf.zeros` does not produce tensors with zeros but some nonzero random numbers. That's why I made
> 
> https://github.com/BachiLi/redner/blob/1533a827680b57ba81d98e41fe3954ae488b282d/pyrednertensorflow/__init__.py#L31-L39
> 
> I don't know how to reproduce this bug. This may not happen on your machine. However, this workaround may be an imperfect solution for GPU computing.

It's very hard to imagine how such a commonly-used function can be buggy. I prefer to keep it as it for now until people complain. I'll make sure the g buffer test works.

**Comment by SuperShinyEyes** [comment]
> It's very hard to imagine how such a commonly-used function can be buggy. I prefer to keep it as it for now until people complain. I'll make sure the g buffer test works.

I agree it's hard to imagine. Neither our lab could believe what we saw.

**Comment by BachiLi** [comment]
Almost done with the GPU port. Just need to rewrite all the tests/tutorials/examples.

**Comment by BachiLi** [comment]
It seems that the eager mode scalar cache in tensorflow sometimes get corrupted, causing the tf.zeros bug mentioned earilier. Not sure if this is a memory bug in our code or something else. I'm tracking this right now.

**Comment by SuperShinyEyes** [comment]
I don't think it's a memory issue caused by the custom OPs. There were corrupted zero tensors which were never passed to C++. For example, in shape.py.

**Comment by BachiLi** [comment]
I probably know the cause. It is caused by the custom operations. Those corrupted zero tensors share the same memory address with some tensors passed into the custom ops, which is then modified by the C++ code. I also know how to fix this, but it's 9pm so I'll take a short break ; )

**Comment by SuperShinyEyes** [comment]
Haha you should call it a day 😄

BTW, how do you verify your hypothesis? Is there some tool to analyze memory structure?

I'm very interested to know how to debug this kind of error.

**Comment by BachiLi** [comment]
I didn't use any tools here except pdb, gdb and printfs. I got the scalar cache thing by tracing through tensorflow, then I realize the corruption happened after the backward pass. I then tried to comment out part of the C++ code to bisect the part that causes the corruption. I also created new tf.zeros(1) to confirm that the memory addresses are reused.

**Comment by SuperShinyEyes** [comment]
I see! After spending 1 hour of reading the source code, I finally understand the cause. Thank you! Very good tracing!

**Comment by SuperShinyEyes** [comment]
> It seems that the eager mode scalar cache in tensorflow (https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/framework/constant_op.py#L99) 

Just out of curiosity, do you know why they call it *scalar_cache* when it's a tensor not scalar?

**Comment by BachiLi** [comment]
> > It seems that the eager mode scalar cache in tensorflow (https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/framework/constant_op.py#L99)
> 
> Just out of curiosity, do you know why they call it _scalar_cache_ when it's a tensor not scalar?

It's for tensors whose whole entries containing the same value, and "constant" has been used for something else...

**Comment by BachiLi** [comment]
Finally merged. I'll move on to the docker thing next week.

**Comment by SuperShinyEyes** [comment]
This is awesome 👏👏👏 Now enjoy your weekend 🏖

**Pull request merged**
